### ISSUE TITLE
Cherrypick dark-mode changes

### ISSUE THREAD

**Issue by deepakjois** [deepakjois/writing#1]
@Steve2955 Here is a commit in my fork which cleans up your patch and just retains the essential changes: https://github.com/deepakjois/writing/commit/82ffcc615e56f82359cf3d2688f86beb589aecf6

I don’t want to claim credit for your patch, so it is best if you cherry pick in your code. Here is a list of steps you could follow, if you are having difficulty with Git.

First, add my repo to your remote:

```
git remote add dj https://github.com/deepakjois/writing
```

Then reset your master branch to the base commit in the original repo, and cherry-pick my changes (without committing them). and then commit them under your name:

```
git reset --hard 7045bfbefa63a5540c0dbbb502e488e600f745da
git cherry-pick --no-commit  dj/master
git add .
git commit -m "Enable dark mode changes"
```

Then do a force push to your remote repo, and the pull request will be automatically updated:
```
git push -f origin master
```

**Comment by deepakjois** [comment]
If you are still having trouble, please add me as a collaborator to your repo and I will commit it directly there with you as the author.

**Comment by Steve2955** [comment]
Thank you so much for your help. This is the first time I'm contributing to an open source project and I didn't expect that much kind support. I will probably do this more often in the future, I really enjoy it so far.
